language: ruby
cache: bundler
rvm:
- 2.4.0

sudo: false

before_install:
  - openssl aes-256-cbc -K $encrypted_bf139d144395_key -iv $encrypted_bf139d144395_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d

script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: .travis/deploy.sh


addons:
  ssh_known_hosts: tatooine.sevenbyte.org
