# Site settings
title: ~rumpelsepp/braindumps
email: rumpelsepp@sevenbyte.org
description: Random bits from deep inside my brain
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.sevenbyte.org" # the base hostname & protocol for your site
github_username:  rumpelsepp

timezone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
    #   author: "Stefan Tatschner"

# Build settings
gems:
    - jekyll-asciidoc

asciidoctor:
  attributes:
    - icons=font
    - hardbreaks!
    - hardbreaks-option!
    - source-highlighter=highlight.js
