# Site settings
title: ~rumpelsepp/brain
email: rumpelsepp@sevenbyte.org
description: Random bits from deep inside my brain
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  rumpelsepp

timezone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
    #   author: "Stefan Tatschner"

# Build settings
gems:
    - jekyll-asciidoc
    - jekyll-feed

asciidoctor:
  attributes:
    icons: "font"
    source-highlighter: "highlight.js"
    imagesdir: /assets/img

exclude:
  - vendor
  - manage.sh
  - Gemfile
  - Gemfile.lock
