= Impressum
:page-layout: page

German law demands this crap! So, here it is. Eat it and leave me alone lawyers...

== Angaben gemäß § 5 TMG

[%hardbreaks]
Stefan Tatschner
Granitweg 20
94481 Grafenau
E-Mail: rumpelsepp@sevenbyte.org

Quelle: http://www.e-recht24.de

== Haftungsausschluss (Disclaimer)
=== Haftung für Inhalte

Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen
Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind
wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder
gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen,
die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung
oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen
bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem
Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei
Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte
umgehend entfernen.

=== Haftung für Links

Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir
keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine
Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige
Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden
zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft.
Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine
permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete
Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von
Rechtsverletzungen werden wir derartige Links umgehend entfernen.

=== Urheberrecht

Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten
unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung,
Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes
bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers.
Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen
Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber
erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden
Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine
Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden
Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte
umgehend entfernen.

== Datenschutzerklärung
=== Server-Log-Files

Der Provider der Seiten erhebt und speichert automatisch Informationen in so
genannten Server-Log Files, die Ihr Browser automatisch an uns übermittelt.
Dies sind:

* Browsertyp und Browserversion
* verwendetes Betriebssystem
* Referrer URL
* Hostname des zugreifenden Rechners
* Uhrzeit der Serveranfrage

Diese Daten sind nicht bestimmten Personen zuordenbar. Eine Zusammenführung
dieser Daten mit anderen Datenquellen wird nicht vorgenommen. Wir behalten uns
vor, diese Daten nachträglich zu prüfen, wenn uns konkrete Anhaltspunkte für
eine rechtswidrige Nutzung bekannt werden.

=== Datenschutzerklärung für die Nutzung von Piwik

Diese Website benutzt den Open Source Webanalysedienst Piwik. Piwik verwendet
so genannte "Cookies". Das sind Textdateien, die auf Ihrem Computer gespeichert
werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen.
Dazu werden die durch den Cookie erzeugten Informationen über die Benutzung
dieser Website auf unserem Server gespeichert. Die IP-Adresse wird vor der
Speicherung anonymisiert.

Die durch den Cookie erzeugten Informationen über die Benutzung dieser Website
werden nicht an Dritte weitergegeben. Sie können die Speicherung der Cookies
durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir
weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht
sämtliche Funktionen dieser Website vollumfänglich werden nutzen können.

Wenn Sie mit der Speicherung und Nutzung Ihrer Daten nicht einverstanden sind,
können Sie die Speicherung und Nutzung hier deaktivieren. In diesem Fall wird
in Ihrem Browser ein Opt-Out-Cookie hinterlegt der verhindert, dass Piwik
Nutzungsdaten speichert. Wenn Sie Ihre Cookies löschen hat dies zur Folge, dass
auch das Piwik Opt-Out-Cookie gelöscht wird. Das Opt-Out muss bei einem
erneuten Besuch unserer Seite wieder aktiviert werden.

++++
<iframe style="border: 0; height: 200px; width: 600px;" src="https://piwik.sevenbyte.org/index.php?module=CoreAdminHome&action=optOut&language=en"></iframe>
++++

=== Widerspruch Werbe-Emails

Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten
zur Übersendung von nicht ausdrücklich angeforderter Werbung und
Informationsmaterialien wird hiermit widersprochen. Die Betreiber der Seiten
behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten
Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.

Quelle: http://www.e-recht24.de
