= Awesome Stuff No 1

That's the Awesome Stuff #1. Awesome Stuff is an ongoing series of
blogposts that introduces several awesome, crazy or senseless tools.

Have Fun!


https://github.com/wting/autojump[autojump]::
    A cd command that learns - easily navigate directories
    from the commandline.

https://github.com/borgbackup/borg[borgbackup]::
    Deduplicating backup program with optional compression
    and authenticated encryption support.

https://github.com/andsens/homeshick[homeshick]::
    git dotfiles synchronizer written in bash

https://github.com/zsh-users/zsh-history-substring-search[history-substring-search]::
    ZSH port of Fish shell's history search feature

http://newsbeuter.org/[newsbeuter]::
    Newsbeuter is an open-source RSS/Atom feed reader for
    text terminals. It runs on Linux, FreeBSD, Mac OS X and other Unix-
    like operating systems. Newsbeuter's great configurability and vast
    number of features make it a perfect choice for people that need a
    slick and fast feed reader that can be completely controlled via
    keyboard.

https://github.com/sorin-ionescu/prezto[prezto]::
    Instantly Awesome Zsh

https://davedavenport.github.io/rofi/[rofi]::
    A window switcher, run dialog and dmenu replacement

https://syncthing.net[Syncthing]::
    Open Source Continuous File Synchronization

https://github.com/syncthing/syncthing-inotify[syncthing-inotify]::
    Inotify support for Syncthing

https://github.com/nvbn/thefuck[thefuck]::
    Magnificent app which corrects your previous console command

https://christian.amsuess.com/tools/arandr/[arandr]::
    Manage display layout graphically and export the settings as 
    a shellscript; the shellscript uses `xrandr` to replicate
    the settings.
