= Autogenerate Manpages from Github
:icons: font

A few people might have noticed, though it is quite unlikely, that the manpages
of my Github projects
footnote:[https://github.com/rumpelsepp/pynote]footnote:[https://github.com/rumpelsepp/c.py]footnote:[https://github.com/rumpelsepp/snap]
are automatically rendered to HTML footnote:[https://docs.sevenbyte.org] (with a slight delay) when a new git push
has happened. Thanks to the `asciidoctor` project, a few lines of `Makefile`
code and a litte shell script which is run by `cron`.

This shellscript checks every hour if a new push has been done on Github. When
there is new code available, it pulls the changes runs the maketarget and finally
copies the generated HTML files to the webroot of my vhost.

[source, sh]
.update-man.sh
----
#!/bin/sh

HTDOCS="$HOME/htdocs/docs"  # <1>
CACHEDIR="/var/tmp/mans"    # <2>

for project in "c.py" "pynote" "snap"; do
    if [ ! -d "$CACHEDIR/$project" ]; then
        git clone "https://github.com/rumpelsepp/$project" "$CACHEDIR/$project"
    fi

    cd "$CACHEDIR/$project/man" || cd "$CACHEDIR/$project/docs" || exit 1

    prev="$(git rev-list HEAD -n 1)"
    git pull
    head="$(git rev-list HEAD -n 1)"
 
    # http://stackoverflow.com/a/20995691
    if [ "$prev" = "$head" ]; then  # <3>
        echo "No changes detected."
        echo "Continue with next project..."
        continue
    fi

    gmake html  # <4>
    cp *.html "$HTDOCS/$project/"
done
----
<1> The docroot of the vhost of the webserver
<2> The directory where the downloaded git repositories are stored. I have chosen
    `/var/tmp` since it does not hurt me... 
<3> This block checks whether the `git pull` operation has pulled new stuff. I have
    found this on stackoverflow. The variables are assigned above.
<4> I use FreeBSD, so there is `gmake` for GNU make; on Linux replace this with `make`.

The `Makefile` that actually invokes `asciidoctor` can be found on
https://raw.githubusercontent.com/rumpelsepp/snap/master/man/Makefile[Github].
It is the same for each of the projects. 

Last but not least, do not forget to create a `crontab` entry, e.g. like this:

----
@hourly $HOME/scripts/update-man.sh > /dev/null 2>&1
----
