= Vollautomatisierter FreeBSD Paket Build-Server
:page-lang: de

Ich schreib zwar sowieso irgendwann ein paar Blogeinträge drüber, aber
ich muss das jetzt hier mal so als Braindump loswerden...

Ich bin aktuell ja immer noch dabei meinen Monsterverhau an Linux Server
umzuziehen auf FreeBSD. Angefangen habe ich vor 9 Monaten oder so.
Langsam aber sicher werde ich tatsächlich fertig, nur jetzt mach ich
andauernd ein Fass nach dem anderen auf. Nachdem ich jetzt meine
Firewallkonzepte hin und herwerfe (IPFW vs PF vs IPFW vs ...), habe ich
jetzt auch mein Paketmanagment komplett anders organisiert. Ich muss
sagen, es ist geil!

Aus einem vServer sinds mittlerweile zwei und ein kleiner Rootserver
geworden (Webserver, Mailserver, Backup-/Buildserver). Ich bin da dabei
alles mal "ordentlich" zu machen, darunter auch so Geschichten, wie
letztens auf der Mailingliste, mit NTP, openssl vs libressl, unnütze
Buildoptionen von Paketen deaktivieren, ...

Bei FreeBSD kann man über das Port-System super geil Pakete selbst baun.
Selbst gebaute Pakete integrieren sich nahtlos ins Paketmanagmentsystem
-- https://wiki.freebsd.org/pkgng[`pkg`].

Für die, die es nicht kennen der Workflow ist so (Port="selbst bauen"):

Binär:

    pkg install FOO

Port:

    cd /usr/ports/FOO && make install clean

Pakete können sehr einfach konfiguriert werden (make config); man wird
beim Konfigurieren interaktiv durchgeführt und kann in einer TUI ganz
einfach Paketoptionen aktivieren und deaktivieren; Optionen können auch
global in der /etc/make.conf gesetzt werden, was ein Gentoo ähnliches
USE-Flag Feeling erzeugt. Ich kann damit z.B. die Standard php, python,
ruby, ... Version einstellen. So könnte man relativ einfach ohne
dependency hell alte Systeme supporten.

Offiziell ist es so, dass der Portstree (= die Makefiles zum selber
bauen) rolling release ist. Die offiziellen binär Pakete sind (mit
Security Patches) auf jeweils ein Quartal gefreezed. Wenn man also mal
ein aktuelleres Paket braucht, baut mans schnell aus dem Porttree selber.

Warum schreib ich jetzt das ganze? Ich hab mal wieder ein Fass
aufgemacht, weil ich unbedingt libressl nutzen wollte und meine Pakete
zusätzlich, durch getweakte Buildoptionen minimalisieren wollte. Ihr
wisst ja, "Komplexität ist der Feind" [fefe] ... Wenn ich jetzt hergeh
und auf drei separaten Servern jedes mal dieses ganze Build-Prozedere
durchgehen muss, werde ich narrisch. Die Lösung ist das Tool
https://github.com/freebsd/poudriere[`poudriere`].

Das Teil ist ein übelst, mega mächtiges Build-Shellscript für den
Portstree. Es erstellt automatisch eine Jail zum bauen (eine Jail ist
das, was Docker eigentlich sein will...). Es können FAST ALLE Versionen
von FreeBSD für die Build Jail ausgewählt werden, d.h. man kann für alle
möglichen Releases automatisch Pakete bauen. Das Tool funktioniert
vollautomatisch zum Deployen in einen Serverpool; da die Dokumentation
von FreeBSD einfach nur göttlich ist, habe ichs innerhalb von 30 Minuten
am Laufen gehabt.

Der Workflow ist wie folgt:

- Build Jail erstellen, mit gewünschem FreeBSD Release; oder mehrere
- Portstree laden (rolling, oder quartal; oder beides, ...)
- Die Pakete, die man haben will in ein txt File eintragen
- Optional Pakete konfigurieren (libressl statt openssl, no X11, ...)
- Start
- Warten:

----
[00:00:00] ====>> Creating the reference jail... done
[00:00:11] ====>> Mounting system devices for freebsd_10-3x64-HEAD
[00:00:12] ====>> Mounting ports/packages/distfiles
[00:00:12] ====>> Using packages from previously failed build
[00:00:12] ====>> Mounting packages from: /usr/local/poudriere
[...]
[00:01:29] ====>> [01][00:00:00] Starting build of ports-mgmt/pkg
[00:05:26] ====>> [01][00:03:57] Finished build of ports-mgmt/pkg: Success
[00:05:27] ====>> [03][00:00:00] Starting build of lang/perl5.20
[00:05:27] ====>> [04][00:00:00] Starting build of devel/gmake-lite
[00:05:39] ====>> [02][00:00:12] Finished build of devel/pkgconf: Success
[00:05:39] ====>> [01][00:00:12] Finished build of print/indexinfo: Success
----

- poudriere generiert nach jedem Build einen detaillierten
  https://pkg.sevenbyte.org/build.html?mastername=freebsd_10-3x64-HEAD&build=2016-08-07_12h19m00s[Bericht]

Das poudriere Repository kann man jetzt im gesamten Serverpool als
Paketquelle einstellen (optional signiert poudriere die Pakete auch).
Ein Cronjob auf dem poudriere Server updated die Pakete alle paar Tage
automatisch und kompiliert ggf. Abhängigkeiten neu. Im Serverpool kann
ich nun meine eigens konfigurierten Pakete mit dem Paketmanagment
einspielen. Was mir hier auch noch gut gefällt, ist dass die URL
Endpunkte so sinnvoll generiert werden, dass ich damit mehrere FreeBSD
Releases mit Paketen versorgen könnte. Ich könnte also in meinem Pool
ein 10.2, 10.3 oder ein 11.0 Release gleichzeitig mit dem gleichen
poudriere Server mit Paketen versorgen; ich kann sogar den
Paketfreezestatus (rolling, quartal, ...) unabhängig switchen.

Ich bereue den Schritt zu BSD bis jetzt kein bisschen. Das Paketsystem
ist ziemlich anders, aber so mächtig und kinderleicht zu handhaben. Ich
hab jetzt mit minimalem Aufwand (ca. sieben bis acht serielle Befehle,
ein Configfile, ein TXT-File mit der Paketliste und drei Zeilen Crontab)
einen vollautomatisierten Paketbuildserver, der meine drei
produktiv-Server mit Updates versorgt. => geil! Beat this, Debian! :D

Auf Digital Ocean und im offiziellen Handbuch gibts noch gute
Anleitungen zu poudriere:

* https://www.freebsd.org/cgi/man.cgi?query=poudriere&sektion=8&manpath=freebsd-release-ports
* https://www.freebsd.org/doc/handbook/ports-poudriere.html
* https://www.digitalocean.com/community/tutorials/how-to-set-up-a-poudriere-build-system-to-create-packages-for-your-freebsd-servers
