= Awesome Stuff No 4
:page-liquid:
:experimental:
:page-lang: de
:toc: macro

Hier ist die Awesome Stuff #4. Ich werde in unregelmäßigen Abständen
coole, sinnvolle oder abgefahrene Linux Tools auflisten, die ich immer
mal wieder ausgrab. Heute im Programm:

toc::[]

Der war lange ueberfaellig und ist seit Ewigkeiten halb fertig im Draft
Ordner versauert. Jetzt hab ich ihn in der U-Bahn mal fertig geklopft.
Sorry fuer Typos, das fehlen von Umlauten und dafuer dass es mal wieder
auf Deutsch ist... :D

Viel Spaß damit!

== Neovim

https://neovim.io::
	Jo, ein Fork von vim, wo mal ordentlich aufgeraeumt wird. Lauft
	mittlerweile sehr stable, mein Haupteditor seit nem halben
	Jahr. Hat atom bei mir vollstaendig abgeloest.

https://github.com/junegunn/vim-plug::
	Plugin Manager fuer [neo]vim. Tut das was es soll.

https://github.com/morhetz/gruvbox::
	Ein Theme, das relativ umfangreich ist und fuer alle Sprachen
	recht gut funktioniert. Der Retro Look ist
	gewoehnungsbeduerftig, aber dafuer ist es wirklich komplett und
	gut. Kontrast kann man einstellen, fette und kursiv Schrift ist
	unterstuetzt (gut in Latex!).

https://github.com/lervag/vimtex::
	Latex fuer vim, ohne den Editor in ein IDE Monster zu
	verwandeln.

https://github.com/Shougo/deoplete.nvim::
https://github.com/zchee/deoplete-jedi::
	Asynchrone Autocompletion Engine fuer neovim. Funzt super; gibt
	Go und Python Extensions dafuer. Hab jetzt mal nur die Python
	Variante verlinkt.

https://github.com/editorconfig/editorconfig-vim::
http://editorconfig.org::
	Editorconfig Unterstuetzung. Damit kann man in einem Projekt
	eine gemeinsame Konfiguration machen. Ist richtig cool, wenn
	die Contributer mal wieder alles kaputt machen (whitespace,
	Tabsize, ....).

https://github.com/scrooloose/nerdcommenter::
	Mit einem Command alles auskommentieren. Der Kommentarstil kann
	umfangreich eingestellt werden.

https://github.com/jiangmiao/auto-pairs::
	Tut Klammern immer gleich als Paar einfuegen. So, dass man sich
	ned immer die Fingern abbricht. Bin mir nur noch ned sicher, ob
	man dazu ein Plugin braucht; fuer den Moment hab ichs mal drin.

https://github.com/mhinz/vim-galore/blob/master/README.md::
	Sehr coole Einfuehrung zu vim auf Github.

== i3 Foo

http://swaywm.org/::
	Eine i3 Implementierung fuer Wayland. Kommt gut voran, ist aber
	noch nicht brauchbar fuer daily use.

https://github.com/eXeC64/imv::
	Ein Bildbetrachter, aehnlich wie sxiv, aber auch unter Wayland
	lauffaehig.

https://github.com/naelstrof/maim::
	Screenshot Tool, modularer als scrot und wird aktiv
	weiterentwickelt.

== Shell-Foo

https://github.com/junegunn/fzf::
https://github.com/junegunn/fzf.vim::
	Jo Leute, das Teil ist *DER* Shit. Ein Tool, in das man Text
	reinpipen kann, es macht eine Liste auf, die man fuzzy
	durchsuchen kann. Das Ergebnis nach betaetigen der Enter Taste
	landet in der Standardausgabe. Damit kann man viele coole
	Sachen machen... Das Teil ist bei mir in der Shell auf
	kbd:[ctrl + r] gebunden fuer Shell Completion (gibt Fish
	Keybindings), ich hab es im Vim als Plugin, ... Lohnt sich es
	sich mal anzuschaun und in den jew. Workflow einzubauen. Der
	Ludwig scheint es auch schon zu moegen...
	Auf dem Github Wiki gibt es viele Beispiele.

https://rash.readthedocs.io/en/latest/::
	"Advanced Shell History"

http://xon.sh/::
	Eine Shell... wo man Python Code schreiben kann. Aber nicht wie
	ipython, sondern sowas wie Bash, ... wo man Python Code
	schreiben kann. Total abgefahren.

== Sinnvolle Bibliotheken

https://pycco-docs.github.io/pycco/::
	Ziemlich cooler Dokumentations Generator fuer Python. Schaut
	recht intuitiv aus, was er erzeugt.

http://pandas.pydata.org/::
	Datenanalyse in Python; Design Goal ist es keine Loops
	schreiben zu muessen. Hier ist mal ein Intro dazu:
	https://www.youtube.com/watch?v=rEalbu8UGeo

https://arrow.readthedocs.io/en/latest/::
	Python Datumslibrary. Ist ziemlich einfach und cool zu nutzen.

http://bokeh.pydata.org::
https://plot.ly/python/::
	Mal wieder iwas zum plotten in Python...

http://awesome-go.com/::
	Die Dinger sind cool. Einfach ne Liste an Libraries fuer Go

https://github.com/uhub/awesome-python::
	(...) fuer Python

== Sonstiges

https://github.com/mlafeldt/sharness::
	Test suite fuer Bash. Damit kann man ziemlich cool CLI
	Programme testen. Die Git Devs nehmen das u.a. her.

http://joss.theoj.org/papers::
	Ein OpenSource Paper Journal (?) Schaut irgendwie interessant
	aus...


== Vorherige Awesome Stuff Mails

* {{ site.url }}{% post_url 2015-10-26-awesome-stuff-1 %}[Awesome Stuff No 1]
* {{ site.url }}{% post_url 2015-11-16-awesome-stuff-2 %}[Awesome Stuff No 2]
* {{ site.url }}{% post_url 2015-12-29-awesome-stuff-3 %}[Awesome Stuff No 3]
